---

- name: Include provision tasks
  ansible.builtin.include_tasks: provision.yml
  when: role_action == 'provision'

- name: Include deprovision tasks
  ansible.builtin.include_tasks: deprovision.yml
  when: role_action == 'deprovision'
